# Generated by Django 6.0.6 on 2026-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_poll_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
