# Generated by Django 6.0.6 on 2026-06-18 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_instagram_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='co_authors',
            field=models.ManyToManyField(blank=True, help_text='Co-authors who co-publish this post', related_name='collaborative_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
