# Generated by Django 6.0.6 on 2026-06-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='is_quote',
            field=models.BooleanField(default=False),
        ),
    ]
