# Generated by Django 6.0.6 on 2026-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='instagram_url',
        ),
    ]
