# Generated by Django 6.0.6 on 2026-06-16 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(help_text='Bootstrap icon class (e.g. bi-star-fill)', max_length=50)),
                ('description', models.TextField()),
                ('criteria', models.CharField(help_text='Short machine-readable criteria key (e.g. posts_10, followers_100)', max_length=200)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for badge display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Verified badge status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_prefs',
            field=models.JSONField(blank=True, default=dict, help_text='Per-type notification preferences'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=10),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('post_created', 'Created a post'), ('post_liked', 'Liked a post'), ('comment_added', 'Commented on a post'), ('follow', 'Followed a user'), ('friend_request', 'Sent a friend request'), ('friend_accept', 'Accepted a friend request'), ('reel_created', 'Created a reel'), ('story_created', 'Created a story'), ('event_created', 'Created an event'), ('event_rsvp', 'RSVPed to an event'), ('badge_earned', 'Earned a badge'), ('group_joined', 'Joined a group'), ('poll_voted', 'Voted on a poll'), ('profile_updated', 'Updated their profile')], max_length=30)),
                ('description', models.TextField()),
                ('target_type', models.CharField(blank=True, help_text='Model name of the target (e.g. Post, Reel, User)', max_length=50)),
                ('target_id', models.IntegerField(blank=True, help_text='PK of the target object', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='users.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
