# Generated by Django 6.0.6 on 2026-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_instagramaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='auto_sync',
            field=models.BooleanField(default=True, help_text='Enable automatic background sync on feed load'),
        ),
    ]
