# Generated by Django 6.0.6 on 2026-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_instagramaccount_auto_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_tags',
            field=models.CharField(blank=True, help_text='Comma-separated interest tags (max 5)', max_length=255),
        ),
    ]
