# Generated by Django 6.0.6 on 2026-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cleanup_duplicate_social_apps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramAccount',
        ),
    ]
