# Generated by Django 6.0.6 on 2026-06-18 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='theme',
            field=models.CharField(default='default', help_text='CSS class/name representing the active chat theme', max_length=50),
        ),
    ]
