# Generated by Django 6.0.6 on 2026-06-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('follow', 'Follow'), ('mention', 'Mention')], max_length=20),
        ),
    ]
