# Generated by Django 6.0.6 on 2026-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('friend_accept', 'Friend Accept'), ('follow', 'Follow'), ('mention', 'Mention'), ('collab_invite', 'Collaboration Invitation')], max_length=20),
        ),
    ]
